CREATE DATABASE mycodeplug;

CREATE USER mycodeplug WITH ENCRYPTED PASSWORD 'DEVsKNOWwHATtHEYREdOING';
CREATE USER mycodeplug_ro WITH ENCRYPTED PASSWORD 'We-re Pr0s';

\connect mycodeplug
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT ALL PRIVILEGES ON SEQUENCES TO mycodeplug;
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT ALL PRIVILEGES ON TABLES TO mycodeplug;

ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT SELECT ON SEQUENCES TO mycodeplug_ro;
ALTER DEFAULT PRIVILEGES
    IN SCHEMA public
    GRANT SELECT ON TABLES TO mycodeplug_ro;
